apiVersion: v1
kind: Service
metadata:
  namespace: fscoding
  name: fscoding-service
  labels:
    run: fscoding
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    run: fscoding
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: fscoding
  name: fscoding
  namespace: fscoding
spec:
  replicas: 4
  selector:
    matchLabels:
      run: fscoding
  template:
    metadata:
      labels:
        run: fscoding
    spec:
      containers:
      - args:
        - /app/app.py
        command:
        - python
        image: nexus.fscoding.com:8085/fscoding:0.6
        name: fscoding
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password

          - name: MYSQL_USER
            value: fscoding

          - name: MYSQL_DATABASE
            value: fscoding

          - name: MYSQL_HOST
            value: fscoding-mysql

          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: fscoding-secret
                key: secret

        ports:
        - containerPort: 8888
          protocol: TCP
      imagePullSecrets:
        - name: nexus-creds
